### ISSUE TITLE
带进度条的轮播图

### ISSUE THREAD

**Issue by hullis** [hullis/vue#16]
##### css代码
```css
* {
  margin: 0;
  padding: 0;
}

a {
  text-decoration: none;
}


#new_slide {
  width: 710px;
  height: 378px;
  overflow: hidden;
  position: relative
}

#new_slide .banner-img {
  position: relative
}

#new_slide .banner-img li {
  float: left;
  width: 710px;
  height: 378px;
  position: relative
}

.txt_bg {
  height: 40px;
  background: #0f0f0f;
  opacity: 0.7;
  filter: alpha(opacity=70);
  margin-top: -40px;
}

#new_slide .banner-img li img {
  width: 710px;
  height: 378px;
  display: block
}

#new_slide .banner-img li a {
  width: 710px;
  height: 30px;
  line-height: 30px;
  font-size: 20px;
  color: #fff;
  font-weight: bold;
  text-align: center;
  overflow: hidden;
  padding: 352px 0 99px;
  position: absolute;
  left: 0;
  top: -10px;
  z-index: 2
}

#new_slide .banner-img li a p {
  height: 30px;
  overflow: hidden
}

#new_slide .banner-btn a {
  display: block;
  line-height: 72px;
  position: absolute;
  top: 173px;
  width: 57px;
  height: 72px;
  background: url(../images/new_icon.png);
  opacity: 0.3;
  filter: alpha(opacity=30);
  color: rgb(255, 255, 255);
  overflow: hidden;
  z-index: 4
}

#new_slide .prevBtn {
  left: 0;
  background-position: 0 -449px !important
}

#new_slide .nextBtn {
  right: 0;
  background-position: -57px -449px !important
}

#new_slide .prevBtn:hover {
  background-position: 0 -521px !important
}

#new_slide .nextBtn:hover {
  right: 0;
  background-position: -57px -521px !important
}

#new_slide .banner-circle {
  position: absolute;
  left: 50%;
  bottom: 15px;
  z-index: 2;
  height: 71px;
  text-align: center;
  font-size: 0;
  overflow: hidden
}

#new_slide .banner-circle li {
  margin: 0 5px;
  display: inline-block;
  display: -moz-inline-stack;
  vertical-align: middle;
  zoom: 1
}

#new_slide .banner-circle li a {
  display: block;
  width: 48px;
  height: 65px;
  border: 3px solid #545353;
  overflow: hidden
}

#new_slide .banner-circle li a img {
  display: block;
  width: 48px;
  height: 65px
}

#new_slide .banner-circle .selected a {
  border-color: #ff4939
}

#new_slide .banner-img li span {
  position: absolute;
  left: 0;
  bottom: 0;
  z-index: 1;
  display: block;
  width: 710px;
  height: 180px;
  background: -webkit-linear-gradient(-90deg, rgba(15, 15, 15, 0) 0, rgba(15, 15, 15, 0.4) 33%, rgba(15, 15, 15, 0.5) 100%);
  background: -moz-linear-gradient(180deg, rgba(15, 15, 15, 0) 0, rgba(15, 15, 15, 0.4) 33%, rgba(15, 15, 15, 0.5) 100%);
  background: linear-gradient(180deg, rgba(15, 15, 15, 0) 0, rgba(15, 15, 15, 0.4) 33%, rgba(15, 15, 15, 0.5) 100%);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#230d0850', GradientType=0)
}

```
##### HTML代码

```html
<!DOCTYPE HTML>
<html>

<head>
  <meta charset="utf-8" />
  <title></title>
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
  <script src="./js/jq.js"></script>
</head>

<body>
  <!-- 幻灯 -->
  <div id="new_slide">
    <!-- 左右按钮 -->
    <div class="banner-btn" style="display: none;">
      <a href="javascript:;" class="prevBtn" rel="nofollow"><i></i>
      </a>
      <a href="javascript:;" class="nextBtn" rel="nofollow" style="opacity: 0.3;"><i></i>
      </a>
    </div>
    <!-- 轮播图 -->
    <ul class="banner-img" style="width: 2130px; left: 0px;">
      <li>
        <img src="http://lorempixel.com/640/480/sports" alt="">
        <a href="javascript:;" title="" target="_blank"></a>
        <div class="slide-txt">
          <div class="txt_bg"></div>
          <a href="javascript:;" title="" target="blank">Cras ultricies ligula sed magna dictum porta</a>
        </div>
      </li>
      <li>
        <img src="http://lorempixel.com/640/480/abstract" alt="">
        <a href="javascript:;" title="" target="_blank"></a>
        <div class="slide-txt">
          <div class="txt_bg"></div>
          <a href="javascript:;" title="" target="blank">Donec sollicitudin molestie malesuada.</a>
        </div>
      </li>
      <li>
        <img src="http://lorempixel.com/640/480/food" alt="">
        <a href="javascript:;" title="" target="_blank"></a>
        <div class="slide-txt">
          <div class="txt_bg"></div>
          <a href="javascript:;" title="" target="blank">Donec sollicitudin molestie malesuada. Pellentesque in ipsum id orci porta dapibus.</a>
        </div>
      </li>
    </ul>
    <!-- 进度条 -->
    <div class="banner-load"></div>
  </div>

</body>

</html>
```

##### js代码

```js
$(function () {
  var $banner = $('#new_slide');
  var $banner_ul = $('.banner-img');
  var $btn = $('.banner-btn');
  var $btn_a = $btn.find('a')
  var v_width = $banner.width();
  var page = 1;
  var timer = null;
  var time = 3000;
  var btnClass = null;
  var page_img = $banner_ul.find('li img');
  var page_count = $banner_ul.find('li').length;
  var load = $banner.find('.banner-load');
  $('.banner-circle').css({
    'width': $banner_ul.find('li').width() * page_count
  });
  var cirLeft = $('.banner-circle').width() * (-0.5);
  $('.banner-circle').css({
    'marginLeft': cirLeft
  });
  $banner_ul.width(page_count * v_width);

  function move(obj, classname) {
    if (!$banner_ul.is(':animated')) {
      loading_start();
      if (classname == 'prevBtn') {
        if (page == 1) {
          $banner_ul.animate({
            left: -v_width * (page_count - 1)
          });
          page = page_count;
          cirMove();
        } else {
          $banner_ul.animate({
            left: '+=' + v_width
          }, "slow");
          page--;
          cirMove();
        }
      } else {
        if (page == page_count) {
          $banner_ul.animate({
            left: 0
          });
          page = 1;
          cirMove();
        } else {
          $banner_ul.animate({
            left: '-=' + v_width
          }, "slow");
          page++;
          cirMove();
        }
      }
    }
  }
  (function loading_reset() {
    load.css({
      "height": "5px",
      "position": "absolute",
      "left": "0",
      "bottom": "0",
      "background": "#FF4939",
      "z-index": "10"
    });
    loading_start();
  })();

  function loading_start() {
    load.animate({
      "width": "100%"
    }, time).animate({
      "width": 0
    }, 0);
  }

  function loading_stop() {
    load.stop(true, true).animate({
      "width": 0
    }, 0)
  }

  function cirMove() {
    $('.banner-circle li').eq(page - 1).addClass('selected').siblings().removeClass('selected');
  }
  $banner.mouseover(function () {
    $btn.css({
      'display': 'block'
    });
    clearInterval(timer);
    loading_stop();
  }).mouseout(function () {
    $btn.css({
      'display': 'none'
    });
    loading_start();
    clearInterval(timer);
    timer = setInterval(move, time);
  }).trigger("mouseout");
  $btn_a.mouseover(function () {
    $(this).animate({
      opacity: 1
    }, 'fast');
    $btn.css({
      'display': 'block'
    });
    return false;
  }).mouseleave(function () {
    $(this).animate({
      opacity: 0.3
    }, 'fast');
    $btn.css({
      'display': 'none'
    });
    return false;
  }).click(function () {
    btnClass = this.className;
    loading_stop();
    clearInterval(timer);
    timer = setInterval(move, time);
    move($(this), this.className);
  });
  $('.banner-circle li').live('click', function () {
    var index = $('.banner-circle li').index(this);
    $banner_ul.animate({
      left: -v_width * index
    }, 'slow');
    page = index + 1;
    cirMove();
  });
});

function tab2(o1, o2, c, t1, t2, a, b) {
  var count = o1.size() - 1;
  var now;
  var TimeInterval;
  o1.each(function (i) {
    $(this).mouseover(function () {
      o2.hide().eq(i).show();
      o1.removeClass(c);
      $(this).addClass(c);
      window.clearInterval(TimeInterval);
    }).mouseout(function () {
      now = i + 1;
      TimeInterval = window.setInterval(changeimage, t1);
    });
    if ($(this).hasClass(c)) {
      $(this).addClass(c);
      o2.hide().eq(i).show();
      now = i + 1;
    }
  })
  o2.each(function (i) {
    $(this).mouseover(function () {
      window.clearInterval(TimeInterval);
    }).mouseout(function () {
      TimeInterval = window.setInterval(changeimage, t1);
    });
  })
  TimeInterval = window.setInterval(changeimage, t1);

  function changeimage() {
    if (now > count) now = 0;
    o2.hide().eq(now).stop().fadeTo(0, a).fadeTo(t2, b);
    o1.removeClass(c).eq(now).addClass(c);
    now++;
  }
}
```
