### ISSUE TITLE
文字上下轮播效果

### ISSUE THREAD

**Issue by hullis** [hullis/vue#22]
##### html代码
```html
<div id="Marquee">
   <div>1.Curabitur non nulla sit amet nisl tempus convallis quis ac lectus</div>
   <div>2.Curabitur non nulla sit amet nisl tempus convallis quis ac lectus</div>
   <div>3.Curabitur non nulla sit amet nisl tempus convallis quis ac lectus</div>
   <div>4.Curabitur non nulla sit amet nisl tempus convallis quis ac lectus</div>
</div>
```

##### js代码
```js
var Mar = document.getElementById("Marquee");
    var child_div = Mar.getElementsByTagName("div")
    var picH = 30; //移动高度 
    var scrollstep = 2; //移动步幅,越大越快 
    var scrolltime = 30; //移动频度(毫秒)越大越慢 
    var stoptime = 3000; //间断时间(毫秒) 
    var tmpH = 0;
    Mar.innerHTML += Mar.innerHTML;

    function start() {
      if (tmpH < picH) {
        tmpH += scrollstep;
        if (tmpH > picH) tmpH = picH;
        Mar.scrollTop = tmpH;
        setTimeout(start, scrolltime);
      } else {
        tmpH = 0;
        Mar.appendChild(child_div[0]);
        Mar.scrollTop = 0;
        setTimeout(start, stoptime);
      }
    }
    onload = function () {
      setTimeout(start, stoptime)
    };
```

##### 基本样式
```css
#Marquee {
      height: 30px;
      overflow: hidden;
    }

    #Marquee div {
      background: #EEECF4;
      line-height: 30px;
    }
```
